#ifndef REPLIES_HPP
#define REPLIES_HPP

// IRC numeric reply codes (RFC 1459 / 2812) currently implemented.
// Server::sendNumericReply() formats these into ":<server> <code> ..." lines.

#define SERVER_NAME "ircserv"

enum IrcNumeric
{
	RPL_WELCOME				= 1,
	RPL_NOTOPIC				= 331,
	RPL_TOPIC				= 332,
	RPL_NAMREPLY			= 353,
	RPL_ENDOFNAMES			= 366,
	ERR_UNKNOWNCOMMAND		= 421,
	ERR_ERRONEUSENICKNAME	= 432,
	ERR_NICKNAMEINUSE		= 433,
	ERR_NEEDMOREPARAMS		= 461,
	ERR_ALREADYREGISTRED	= 462,
	ERR_PASSWDMISMATCH		= 464,
	ERR_NOTREGISTERED		= 451,
	ERR_NOSUCHCHANNEL		= 403,
	ERR_NOTONCHANNEL		= 442,
	ERR_UMODEUNKNOWNFLAG	= 501,
	ERR_CHANOPRIVSNEEDED	= 482,
	ERR_NOSUCHNICK			= 401,
	ERR_USERNOTINCHANNEL	= 441,
	ERR_USERONCHANNEL		= 443,
	ERR_UNKNOWNMODE			= 472,
	ERR_CHANNELISFULL		= 471,
	ERR_INVITEONLYCHAN		= 473,
	ERR_BANNEDFROMCHAN		= 474,
	ERR_BADCHANNELKEY		= 475,
};

#endif
